name: Ansible Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['2.x', '3.x']
        ansible-version: [2.9, 2.4]

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.1.1
    - name: Install Ansible ${{ matrix.ansible-version }}
      run: pip install ansible-lint ansible==${{ matrix.ansible-version }}.*
    - name: ansible-lint
      run: ansible-lint .

