name: Ansible Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1.1.1
    - run: pip install ansible-lint
    - run: ansible-lint --version
    - run: ansible-lint .
#     - name: ansible-lint
#       uses: ansible/ansible-lint-action@v4.1.0.post0
#       with:
#         targets: .
